module.exports = {

  selectors: {

    cookies: {
      acceptCookiesButton: '#onetrust-accept-btn-handler',
      rejectCookiesButton: '#onetrust-reject-all-handler',
      closeCookiesButton: '#onetrust-close-btn-container > .onetrust-close-btn-handler',
      cookiesTitle: '#onetrust-policy-text',
    },

    hotelBookingPanel: {
      panelTabTitle: '//*[@id="shell"]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[1]/button[2]/span',
    },

    flightBookingPanel: {
      panelTabTitle: '.Tab__TabHeader-a3oved-0 fRrfHR',
      roundTripSelect: '.CheckButton__RadioDot-sc-1r227qz-4',
      roundTripText: '[for=roundTrip]',
      oneWaySelect: '.CheckButton__RadioCircle-sc-1r227qz-3',
      oneWayText: '[for=oneWay]',
      cabinClassTitle: '.styles__Label-s6l5iw-4',
      cabinClassText: '[data-testid=default-option]',
      cabinClassIcon: '[data-testid=time-picker-collapse-icon]',
      flyingFromIcon: '[data-testid=icon-FlyingFrom]',
      flyingFromTitle: '[data-testid=location-searchbar-header-text]',
      flyingFromPreText: '.css-1gw5h31-placeholder',
      flyingFromInput: '#react-select-4-input',
      flyingToIcon: '[data-testid=icon-FlyingTo]',
      flyingToTitle: '[data-testid=location-searchbar-header-text]',
      flyingToPreText: '.css-1rlhpux-control',
      flyingToInput: '#react-select-5-input',
      outboundIcon: '',
      outboundTitle: '',
      outboundPreText: '#cwt-date-range-start-date',
      outboundSelectTimeTitle: '',
      outboundSelectTimeIcon: '',
      outboundTimePopUpTitle: '.Styles__Title-gh7d5w-5',
      outboundTimePopUpSubtitle: '.Styles__TimeIndicator-gh7d5w-6',
      outboundTimePopUpDepartSelect: '',
      outboundTimePopUpDepartText: '',
      outboundTimePopUpArriveSelect: '',
      outboundTimePopUpArriveText: '',
      returnIcon: '',
      returnTitle: '',
      returnPreText: '#cwt-date-range-end-date',
      returnSelectTimeTitle: '',
      returnSelectTimeIcon: '',
      returnTimePopUpTitle: '.Styles__Title-gh7d5w-5',
      returnTimePopUpSubtitle: '',
      returnTimePopUpDepartSelect: '',
      returnTimePopUpDepartText: '',
      returnTimePopUpArriveSelect: '',
      returnTimePopUpArriveText: '',
      searchButton: '[data-testid=search-bar-search-btn]',
    },

    hotelSearch: {
      panelTitle: '.styles__Header-sc-1e3o33f-1 > span',
      goingToTitle: '[data-testid=location-searchbar-header-text]',
      goingToIcon: '[data-testid=icon-Hotel]',
      goingToPretext: '.css-1gw5h31-placeholder',
      goingToInput: '[data-testid=search-bar-location] input',
      bookingForInput: '[data-testid=search-bar-ta] > div.css-qc70oq-control > div.css-y7dxqw > div.css-42gxkv-placeholder',
      bookingForFirstOption: '#react-select-8-option-0-0',
      checkinTitle: 'TBD',
      checkinIcon: 'TBS',
      checkinInput: '#cwt-date-range-start-date',
      checkOutTitle: 'TBD',
      checkOutIcon: 'TBS',
      checkOutInput: '#cwt-date-range-end-date',
      searchButton: '[data-testid=search-bar-search-btn]',
      // Search results
      searchResult1: '#react-select-3-option-0',
      searchResult2: '#react-select-3-option-1',
      searchResult3: '#react-select-3-option-2',
      searchResult4: '#react-select-3-option-3',
      searchResult5: '#react-select-3-option-4',
      searchResult6: '#react-select-3-option-5',
      // Search results production
      searchResult1Prod: '#react-select-9-option-0',
      searchResult2Prod: '#react-select-9-option-1',
      searchResult3Prod: '#react-select-9-option-2',
      searchResult4Prod: '#react-select-9-option-3',
      searchResult5Prod: '#react-select-9-option-4',
      searchResult6Prod: '#react-select-9-option-5',
    },

    carSearch: {
      carTab: '[data-testid=hero-content] > div > div > div.styles__StyledWireFrame-sc-1e3o33f-0.gRuHyA > div.TabsBar-sc-5g9tzs-0.dhlArC > button.Tab__TabHeader-a3oved-0.ibQZyR > span',
      carPickUpLocationInput: '[data-testid=search-bar-location] input',
      carPickUpLocationClearButton: '[data-testid=search-bar-location] > div.css-1rlhpux-control > div.css-1wy0on6 > div.css-zwwoie-indicatorContainer > svg > path',
      carPickUpLocationMandatoryLine: '[data-testid=search-bar-location] > hr',
      carDropOffLocationInput: '[data-testid=search-bar-location-wrapper-locationTo] input',
      carDropOffLocationClearButton: '[data-testid=search-bar-location] > div.css-1rlhpux-control > div.css-1wy0on6 > div.css-zwwoie-indicatorContainer > svg > path',
      carLocationNoResultsText: '.Styles__NoMappingMessageWrapper-bfdwqu-4',
      carPickUpDateInput: '#cwt-date-range-start-date',
      carPickUpDateMandatoryLine: '[data-testid=data-field-wrapper] > div > div > div.DateRangePickerInput.DateRangePickerInput_1.DateRangePickerInput__withBorder.DateRangePickerInput__withBorder_2 > div:nth-child(1)',
      carDropOffDateInput: '#cwt-date-range-end-date',
      carPickUpLocationTitle: '[data-testid=location-searchbar-header-text]',
      carDropOffLocationTitle: '[data-testid=location-searchbar-header-text]',
      carPickUpTimeButton: '[data-testid=hero-content] > div > div > div.styles__StyledWireFrame-sc-1e3o33f-0.gRuHyA > div:nth-child(2) > div > div > div.Styles__Wrapper-gh7d5w-0.ivTwnA > div:nth-child(1) > div > span',
      carDropOffTimeButton: '[data-testid=hero-content] > div > div > div.styles__StyledWireFrame-sc-1e3o33f-0.gRuHyA > div:nth-child(2) > div > div > div.Styles__Wrapper-gh7d5w-0.ivTwnA > div:nth-child(2) > div.CwtPickerstyles__Container-sc-1kuf29y-5.jsQBsT > span',
      carPickUpTimeDialogTitle: '[data-testid=tooltip-box] > div.Styles__HeaderContainer-gh 7d5w-4.GrZJV > p > div',
      carDropOffTimeDialogTitle: '[data-testid=tooltip-box] > div.Styles__HeaderContainer-gh7d5w-4.GrZJV > p > div',
      selectPickUpTime2pm: '//*[@id="2_PM_outbound_depart"]/div',
      selectDropOffTime4pm: '//*[@id="4_PM_inbound_depart"]/div',
      findMyCarButton: '[data-testid=search-bar-search-btn] > span',
    },

    welcome: {
      welcomeFullTitle: '[data-testid="hero-welcome-message"] > :nth-child(1)',
      welcomeUsername: '[data-testid="hero-welcome-message"] > :nth-child(1) > :nth-child(2)',
      welcomeGreeting: '[data-testid="hero-greeting-message"]',
      bookFullTripText: '[data-testid="obt-upper-text"]',
      bookFullTripContinueButton: '[aria-label="Continue"]',
      headerVideo: '[data-testid="hero-video-container"]',
    },

    upcomingTrip: {
      upcomingTripTitle: '.TripTitle__Title-k8stgz-0 > b',
      upcomingTripText: '.TripTitle__Title-k8stgz-0 > p',
    },

    alerts: {
      alertsTitle: '[data-testid=travel-alerts-trigger-text]',
      alertsIcon: '[data-testid=icon-Warning]',
      // Alerts tooltip
      alertTooltipTitle: '[data-testid="ta-tooltip-main-title"] > [width="0"] > :nth-child(1) > span',
      alertTooltipIcon: '[data-testid="icon-Medical"]',
      alertTooltipContent: '[data-testid="ta-tooltip-subtitle"]',
      alertTooltipLastUpdated: '[data-testid="ta-tooltip-last-updated"]',
      alertTooltipAlertNumber: '[data-testid="alert-tooltip-alert-number"]',
      alertTooltipShowAllTitle: '[data-testid="alert-tooltip-show-all"]',
      // Alerts popup
      alertPopupDestination: '[data-testid="alert-pager-trip-name"]',
      alertPopupBackwardButton: '[data-testid="icon-Back"]',
      alertPopupForwardButton: '[aria-label="next alert"] > [data-testid="icon-Forward"]',
      alertPopupAlertNumber: '[data-testid="alert-pager-buttons-text"]',
      alertPopupIcon: '[data-testid="icon-Medical"]',
      alertPopupTitle1: '[data-testid="alert-page-category-title"]',
      alertPopupTitle2: '[data-testid="alert-page-modal-title"]',
      alertPopupContent: '[data-testid="alert-page-alert-description"] > div > p',
      alertPopupLastUpdated: '[data-testid="alert-page-last-updated-text"]',
      alertPopupHelpfulTitle: '[data-testid="alert-footer-feedback-text"]',
      alertPopupHelpfulYes: '[data-testid="alert-main-helpful-yes-button"]',
      alertPopupHelpfulNo: '[data-testid="alert-main-helpful-no-button"]',
      alertPopupPoweredBy: '[data-testid="alert-page-footer-poweredby-text"]',
      alertPopupPoweredByImage1: '[data-testid="alert-page-footer-poweredby-img"]',
      alertPopupPoweredByImage2: '[data-testid="alert-page-footer-poweredby-img-risk"]',
      alertPopupCloseButton: '[data-testid="icon-Close"]' },

    navigation: {
      cardsNavigationForward: '#slider-nav-Forward > [data-testid="icon-Forward"]',
      cardsNavigationBack: '[data-testid="icon-Back"]',
    },

    cards: {
      // First flight
      firstFlightIcon: '[data-testid="air-1"] > [data-testid="card-header-box"] > [data-testid="card-header-line-box"] > [data-testid="icon-Plane"]',
      firstFlightTitle: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div[2]/div/div/div[1]/div/div/a[1]/div[1]/div/h4/div/span/span[1]/span',
      firstFlightAirlineIcon: '[data-testid="air-1"] > [data-testid="card-header-box"] > [data-testid="card-header-line-box"] > [data-testid="card-header-segment-vendor-icon"]',
      firstFlightDepartureTime: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      firstFlightArrivalTime: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      firstFlightDepartureDate: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      firstFlightArrivalDate: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      firstFlightDuration: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="duration-column"] > [data-testid="trip-duration-label"] > [data-testid="duration-text"]',
      firstFlightAirportOrigin: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div[2]/div/div/div[1]/div/div/a[1]/div[2]/div[1]/div[2]/div/div/span',
      firstFlightAirportDestination: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div[2]/div/div/div[1]/div/div/a[1]/div[2]/div[3]/div[2]/div/div/span',

      // Second flight
      // Second flight[data-testid="air-1"] > [data-testid="card-header-box"] > [data-testid="card-header-line-box"] > [data-testid="card-header-segment-title"] > [data-testid="tooltip-base"] > [data-testid="tooltip-trigger"]
      // secondFlightIcon: '[data-testid="air-1"] > [data-testid="card-header-box"] > [data-testid="card-header-line-box"] > [data-testid="icon-Plane"]',
      // secondFlightTitle: '[data-testid="hero-welcome-message"] > :nth-child(1) > :nth-child(2)',
      // secondFlightAirlineIcon: '[data-testid="hero-greeting-message"]',
      // secondFlightDepartureTime: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      // secondFlightArrivalTime: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      // secondFlightDepartureDate: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      // secondFlightArrivalDate: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      // secondFlightDuration: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="duration-column"] > [data-testid="trip-duration-label"] > [data-testid="duration-text"]',
      // secondFlightAirportOrigin: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-detail-area"] > :nth-child(1) > [data-testid="tooltip-base"] > [data-testid="tooltip-trigger"]',
      // secondFlightAirportDestination: '[data-testid="air-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-detail-area"] > :nth-child(1) > [data-testid="tooltip-base"] > [data-testid="tooltip-trigger"]',

      // Layover
      layoverIcon: '[data-testid="icon-History"]',
      layoverDurationTime: '[data-testid="duration-time"]',
      layoverDurationText: '[data-testid="card"] > [data-testid="duration-text"]',
      layoverAlert: '[data-testid="alert"]',

      // MissingHotel
      missingHotelImage: '[data-index="2"] > :nth-child(1) > [data-testid="card"] > [data-testid="hotel-img"]',
      missingHotelTitle: '[data-index="2"] > :nth-child(1) > [data-testid="card"] > [data-testid="text-wrapper"] > [data-testid="top-card-wrapper"] > [data-testid="card-title"]',
      missingHotelContent: '[data-index="2"] > :nth-child(1) > [data-testid="card"] > [data-testid="text-wrapper"] > [data-testid="top-card-wrapper"] > .HideOnSize__label-xzz0zf-0 > [data-testid="subtitle"]',
      missingHotelViewHotelsButton: '[data-index="2"] > :nth-child(1) > [data-testid="card"] > [data-testid="text-wrapper"] > [data-testid="footer-wrapper"] > [data-testid="search-button"]',
      missingHotelLocationAndDateText: '[data-index="2"] > :nth-child(1) > [data-testid="card"] > [data-testid="text-wrapper"] > [data-testid="footer-wrapper"] > [data-testid="hotel-checkin-time"]',

      // Car
      carIcon: '[data-testid="icon-Car"]',
      carTitle: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div/div/div/div[4]/div/a/div[1]/div/h4/div/span/span[1]',
      carPickUpTime: '[data-testid="car-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      carDropOffTime: '[data-testid="car-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      carDuration: '[data-testid="car-1"] > [data-testid="card-body-"] > [data-testid="duration-column"] > [data-testid="trip-duration-label"] > [data-testid="duration-text"]',
      carPickUpDate: '[data-testid="car-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      carDropOffDate: '[data-testid="car-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      carPickUpLocation: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div/div/div/div[4]/div/a/div[2]/div[1]/div[2]/div/div',
      carDropOffLocation: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div/div/div/div[4]/div/a/div[2]/div[3]/div[2]/div/div',

      // Hotel
      hotelIcon: '[data-testid="card-header-line-box"] > [data-testid="icon-Hotel"]',
      hotelTitle: '[data-testid="hotel-1"] > [data-testid="card-header-box"] > [data-testid="card-header-line-box"]',
      hotelCheckIn: '[data-testid="card-start-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="date-text-span"]',
      hotelCheckOut: '[data-testid="card-end-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="date-text-span"]',
      hotelDuration: '[data-testid="hotel-1"] > [data-testid="card-body-"] > [data-testid="duration-column"] > [data-testid="trip-duration-label"] > [data-testid="duration-text"]',
      hotelAddress: '.Column__HotelDescription-sc-1d86qku-0 > :nth-child(1) > [data-testid="tooltip-base"]',

      // Rail
      railIcon: '[data-testid="icon-Train"]',
      railTitle: '[data-testid="rail-1"] > [data-testid="card-header-box"] > [data-testid="card-header-line-box"]',
      railDepartureTime: '[data-testid="rail-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      railArrivalTime: '[data-testid="rail-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      railDuration: '[data-testid="rail-1"] > [data-testid="card-body-"] > [data-testid="duration-column"] > [data-testid="trip-duration-label"] > [data-testid="duration-text"]',
      railDepartureDate: '[data-testid="rail-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      railArrivalDate: '[data-testid="rail-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      railOriginStation: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div/div/div/div[7]/div/a/div[2]/div[1]/div[2]/div/div/span',
      railOriginStationProd: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div/div/div/div[6]/div/a/div[2]/div[1]/div[2]/div/div',
      railDestinationStation: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div/div/div/div[7]/div/a/div[2]/div[3]/div[2]/div/div/span',
      railDestinationStationProd: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div/div/div/div[6]/div/a/div[2]/div[3]/div[2]/div/div/span',

      // Meeting
      meetingIcon: '[data-testid="icon-Meeting"]',
      meetingTitle: '[data-testid="meeting-1"] > [data-testid="card-header-box"] > [data-testid="card-header-line-box"]',
      meetingStartTime: '[data-testid="meeting-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      meetingEndTime: '[data-testid="meeting-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-main-text"] > [data-testid="time-text"]',
      meetingDuration: '[data-testid="meeting-1"] > [data-testid="card-body-"] > [data-testid="duration-column"] > [data-testid="trip-duration-label"] > [data-testid="duration-text"]',
      meetingStartDate: '[data-testid="meeting-1"] > [data-testid="card-body-"] > [data-testid="card-start-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      meetingEndDate: '[data-testid="meeting-1"] > [data-testid="card-body-"] > [data-testid="card-end-column-wrapper"] > [data-testid="column-secondary-area"] > [data-testid="card-date-text"]',
      meetingAddress: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div[1]/div/div/div[8]/div/a/div[3]/div[1]/div/span',
      meetingAddressProd: '//*[@id="shell"]/div[2]/div/div/section[1]/div/div[2]/div/div/div/div[7]/div/a/div[3]/div[1]/div/span',
      meetingContact: '.meeting__ContactList-sc-5kvj2a-0',
    },

    companyNews: {
      companyNewsTitle: '[data-testid="company-news-title"]',
      companyNewsArticleTitle: '[data-testsid="company-news-message-0"] > .Item__CompanyNewsItemContent-sc-95cgzh-1 > [data-testid="company-news-item-title"]',
      companyNewsArticleDate: '[data-testsid="company-news-message-0"] > .Item__CompanyNewsItemContent-sc-95cgzh-1 > [data-testid="company-news-item-date"]',
      companyNewsArticleContent: '[data-testsid="company-news-message-0"] > .Item__CompanyNewsItemContent-sc-95cgzh-1 > [data-testid="collapse-wrapper"]',
      companyNewsShowMoreButton: '[data-testsid="company-news-message-0"] > .Item__CompanyNewsItemContent-sc-95cgzh-1 > [data-testid="button-anchor"]',
      companyNewsShowLessButton: '[data-testsid="company-news-message-0"] > .Item__CompanyNewsItemContent-sc-95cgzh-1 > [data-testid="button-anchor"]',
    },

    companyResources: {
      companyResourcesTitle: '[data-testid="company-resources-title"]',
      companyResourcesLinksToggle: '[data-testid="collapse-panel-toggle"]',
      companyResourcesIcon1: '[data-testid="company-resource-link-752956"] > [data-testid="icon-ArrowRight"]',
      companyResourcesLink1: '[data-testid="company-resource-text-3fbsx2empx9o902p2fekwj4x4dwbe33r"]',
      companyResourcesLink1Prod: '[data-testid="company-resource-text-36256"]',
      companyResourcesIcon2: '[data-testid="company-resource-link-9301905"] > [data-testid="icon-ArrowRight"]',
      companyResourcesLink2: '[data-testid="company-resource-text-9301905"]',
      companyResourcesIcon3: '[data-testid="company-resource-link-11096680"] > [data-testid="icon-ArrowRight"]',
      companyResourcesLink3: '[data-testid="company-resource-text-11096680"]',
    },

    chat: {
      openChatButton: '#messenger-button',
      headerCloseButton: '.close-icon',
      headerImage: '.header-icon',
      headerText: '.header-content',
      textInput: '.message-input',
      uploadIcon: '.upload-icon',
      locationTextUpload: 'TBD',
      fileTextUpload: 'TBD',
      imageTextUpload: 'TBD',
    },

    autoLogout: {
      extendButton: '.action-extend-session',
      logoutButton: '.action-extend-logout',
    },
  }
};